### ISSUE TITLE
Dataset format

### ISSUE THREAD

**Issue by tonmoy-saikia** [princeton-computational-imaging/SeeingThroughFog#1]
Hi thanks for this dataset! 

I am trying to figure out where RGB images and 2D bounding box labels are located in the download folder.
I see the following contents after downloading `SeeingThroughFogCompressed`. 
```
calib_cam_stereo_left.json
calib_gated_bwv.json
calib_tf_tree_full.json
filtered_relevant_can_data.zip
gated_full_acc_rect.zip
gt_labels_cmore_copied_together.zip
labeltool_labels.zip
lidar_hdl64_last_gated.zip
lidar_hdl64_last_stereo_left.zip
lidar_hdl64_strongest_gated.zip
lidar_hdl64_strongest_stereo_left.zip
radar_targets.zip
road_friction.zip
weather_station.zip
```

**Comment by fabvio** [comment]
Same for me, thanks for the amazing work! Having the RGB images as well would be great, but they do not seem to be included in `SeeingThroughFogCompressed`.

**Comment by MarioBijelic** [comment]
Hi guys, thank you pointing out the issue. We have localized the problem and dataset will be reuploaded mid of next week. The rgb camera images will be in the zip files cam_sterero_position_encoding. The gated images will be in gatedsliceid_encoding. FIR images are in fir_axis.

Best,
Mario

**Comment by MarioBijelic** [comment]
Hi guys, 

the dataset is fully reuploaded. This issue should be fixed now. 

Best, 
Mario

**Comment by tonmoy-saikia** [comment]
@MarioBijelic I cannot find `cam_sterero_position_encoding`. I downloaded `cam_stereo_left` but seems like the folder contains only single-channel images.

**Comment by MarioBijelic** [comment]
Hi @tonmoy-saikia, this folder contains the raw 12bit undebayered data and is therefore missing the _encoding flag. To enable easier use I have added a Raw2LUT tool. It takes the raw input image and applies the needed process to get human readable 8bit images.

**Comment by veesohoni** [comment]
Hello All, 

I use SSH and work on a remote machine. I want to download `SeeingThroughFogCompressed` but I am not able to get the link.
I can see only the direct download option on the website. Please let me know how should I download

**Comment by veesohoni** [comment]
Also I am getting following error while unzipping the individual folder files

download: Zip archive data, at least v4.5 to extract
