### ISSUE TITLE
Have a queation about thermal data

### ISSUE THREAD

**Issue by yeong-dev** [princeton-computational-imaging/SeeingThroughFog#10]
Hello, I have a question about your dataset (This is not a real issue)
DENSE dataset is super attractive so that i really want to use this dataset.
BTW, your dataset includes thermal dataset in 8 bit, however, Do you have 14 bit format Thermal data?
14 bit thermal data contains more detailed data, thus, i am really curious about this.
If you have, Could you share the dataset?

-PS. DENSE dataset is really cool I'm trying to do calibrate thermal data with stereo image for my research

**Comment by MarioBijelic** [comment]
Hi, unfortunately we are only able to provide the 8 bit data. Please take into account, that we used a security camera (Axis Q1922) and therefore the camera is missing certain cleaning features usually build into serial vehicles. Hence, thin water and ice layers diminish performance. Probably you will have to filter those examples. 
P.S. thank you for your kind words. Already looking forward to your contribution. 
Best, Mario

**Comment by yeong-dev** [comment]
Thanks for the kind answer! ;D I am also expecting your brilliant research
