### ISSUE TITLE
OpenGL issue. AttributeError: 'list' object has no attribute 'x'

### ISSUE THREAD

**Issue by manonthegithub** [princeton-computational-imaging/SeeingThroughFog#15]
I am trying to run DatasetViewer.

Even though the window with the images is running. 
I am getting many of these errors in the console:
```
Traceback (most recent call last):
  File "/Users/kirill/.conda/envs/SeeingThroughFog/lib/python3.6/site-packages/pyqtgraph/opengl/GLViewWidget.py", line 189, in paintGL
    self.setModelview()
  File "/Users/kirill/.conda/envs/SeeingThroughFog/lib/python3.6/site-packages/pyqtgraph/opengl/GLViewWidget.py", line 142, in setModelview
    m = self.viewMatrix()
  File "/Users/kirill/.conda/envs/SeeingThroughFog/lib/python3.6/site-packages/pyqtgraph/opengl/GLViewWidget.py", line 152, in viewMatrix
    tr.translate(-center.x(), -center.y(), -center.z())
AttributeError: 'list' object has no attribute 'x'
```

Looks like something works wrong. No idea how to fix it. I have tried a few versions of pyopengl, but it didn't help

**Comment by MartinHahner** [comment]
I encountered the same issue a while ago.

Change this line
https://github.com/princeton-computational-imaging/SeeingThroughFog/blob/a6deecfdcbab4b275ac297690d5a8584f98ecf44/tools/DatasetViewer/DataViewer_V2.py#L101

into:

`self.w.setCameraPosition(pos=QtGui.QVector3D(0, 0, 0), distance=10, azimuth=180, elevation=10)`

@MarioBijelic: This should also be changed by the authors of the repository. :wink:

**Comment by MarioBijelic** [comment]
Hi guys, 

this is most probably a Version conflict. For my OpenGL version 3.1.5 and PyQt5 Version 5.14.1 no problems occurs and I am not able to reproduce your problems.
Could you please share your used versions?

**Comment by manonthegithub** [comment]
I have tried several versions. 
Python 3.6, OpenGl 3.1.5 and PyQt 5.9.2 currently gives an error. I think I have tries PyQt 5.14.1 with Python 3.7.

Would be nice if you specify in the repo at least combination of versions you use, which should work.

**Comment by manonthegithub** [comment]
@MartinHahner88 wow great! Thanks a lot, your solution has worked!

**Comment by MartinHahner** [comment]
> Hi guys,
> 
> this is most probably a Version conflict. For my OpenGL version 3.1.5 and PyQt5 Version 5.14.1 no problems occurs and I am not able to reproduce your problems.
> Could you please share your used versions?

What happens if you change this line on your end @MarioBijelic ?
Does it break things in your environment? 
I think it only makes things more robust.

The same error occurs here by the way:
https://github.com/princeton-computational-imaging/SeeingThroughFog/blob/a6deecfdcbab4b275ac297690d5a8584f98ecf44/tools/DatasetFoggification/lidar_foggification.py#L154

**Comment by manonthegithub** [comment]
resolved, PR merged
