### ISSUE TITLE
Radar point cloud format and coordinate frames

### ISSUE THREAD

**Issue by mvitsor** [princeton-computational-imaging/SeeingThroughFog#16]
Hi! Radar targets have the following information: rcsLog, azimuthAngle_sc, rVelOverGroundOdo_sc, x_sc, y_sc, x_cc, y_cc and rDist_sc. I was wondering what the coordinate frames **sc** and **cc** in there mean. 

I'm particularly not sure whether I should use x/y_cc or x/ y_sc when comparing to **posx** and **posy** from the labels in gt_labels/cam_left_labels (e.g. to count how many radar points are inside a bounding box). 

In tools/DatasetViewer/lib/read.py, the function load_calib_data mentions four coordinate frames: _zero_, _camera_, _velodyne_ and _radar_. Can I assume that all label parameters are given in camera coordinates? And what is this _zero_ reference frame?

Thanks for the dataset and for the support!

**Comment by mvitsor** [comment]
Oh, one more thing: I noticed the labels also have an "angle" property, but it seems to be "-1" for all of them. What does this mean?  Does it refer to the 2D image bounding boxes (xleft, xright, ytop, ybottom)? Should this be used at all?

**Comment by MartinHahner** [comment]
> what is this _zero_ reference frame?

As far as I know, _zero_ is located at the center of the rear axle, see here:
https://github.com/princeton-computational-imaging/SeeingThroughFog/blob/a6deecfdcbab4b275ac297690d5a8584f98ecf44/tools/DatasetViewer/calibs/calib_tf_tree_full.json#L602-L625

**Comment by mvitsor** [comment]
Any clue where these sc and cc frames from radar data are located?

**Comment by Nader-13** [comment]
Great work guys!!
Can you please elaborate a little bit more on the Radar data format?

**Comment by MarioBijelic** [comment]
Hi, 

the coordinate systems are chosen such that sc = sensor coordinates and cc is transformed to car coorditnates. Car coordinates are given relative to the body.
