### ISSUE TITLE
3D information missing from labels

### ISSUE THREAD

**Issue by mvitsor** [princeton-computational-imaging/SeeingThroughFog#17]
Some labels apparently don't have information to draw the 3D bounding box in lidar coordinates (height, width, length, posx, posy, poz, and so on)

So instead of looking like this
`PassengerCar 0.00 1 -1 218.00 258.00 313.00 309.00 1.38 1.81 4.16 -11.19 1.31 64.94 -4.676 0.000 0.011 -3.106 1.00 0.0053058781 -0.0000952959 -0.9998246710 0.0179573322 True True True False`
they look like this
`PassengerCar 0.00 -1 -1 388.62 243.29 445.67 290.16 -1.00 -1.00 -1.00 -1000.00 -1000.00 -1000.00 -1.000 -1.000 -1.000 -1.000 1.00 -1000.0000000000 -1000.0000000000 -1000.0000000000 -1000.0000000000 -1 -1 -1 -1`
(it's all -1s and -1000s instead of actual information)

(the lines above are from `/gt_labels/gated_labels_TMP/2018-02-12_15-59-37_00070.txt` as an example)

Does anyone know if this is a bug or if this information is simply unavailable? 

Thanks in advance!

**Comment by MartinHahner** [comment]
> Does anyone know if this is a bug or if this information is simply unavailable?

It's not a bug, 
usually, it means there is not enough data (LiDAR points) in the point cloud for that specific object to determine a confident 3D bounding box.

So in your words, yes, this information is simply unavailable.

**Comment by mvitsor** [comment]
Alright, thanks!
