### ISSUE TITLE
frame_ids where all 3D bounding boxes do not contain a single LiDAR point

### ISSUE THREAD

**Issue by MartinHahner** [princeton-computational-imaging/SeeingThroughFog#18]
There is an issue with frame_id `2018-02-04_10-02-19_00000` in the _validation_day_ split.

The LiDAR scan misses many points and the ground truth 3D boxes do not contain any points.

![image](https://user-images.githubusercontent.com/14181188/96347594-f7055400-10a2-11eb-920a-b86ced8a3378.png)

I will exclude this frame in my LiDAR only 3D object detection pipeline.

**Comment by MartinHahner** [comment]
I found two more frames of that kind, this time in the _test_clear_night_ split.
`2018-02-04_18-18-20_00000` 
![image](https://user-images.githubusercontent.com/14181188/96371247-08ad3100-1161-11eb-9e83-443d69cf8274.png)

`2018-02-04_18-23-32_00000`
![image](https://user-images.githubusercontent.com/14181188/96371260-1a8ed400-1161-11eb-91ee-0e984f85b567.png)

I will also remove them from my LiDAR only object detection pipeline.

**Comment by MarioBijelic** [comment]
Hi Martin,

can you place a pull request. I will merge those chages into the master.

Best, 
Mario

**Comment by MartinHahner** [comment]
@MarioBijelic: [done](https://github.com/princeton-computational-imaging/SeeingThroughFog/pull/20)
