### ISSUE TITLE
where is the train & test code ?

### ISSUE THREAD

**Issue by hoorusosi** [princeton-computational-imaging/SeeingThroughFog#2]
Hi, thanks for nice research and code upload.
I viewed the repository, but couldn't find the main train & estimation code.
where is it ? I'm sorry If I missed something.

**Comment by MarioBijelic** [comment]
Hi, yes you are right. Currently, the repo only contains dataset related code. The Fusion Network is still being refactored and is in progress.

**Comment by amiltonwong** [comment]
HI, @MarioBijelic , any update news on the release of training and testing code?
THX!
