### ISSUE TITLE
Corresponding yaw angle in lidar frame : 3D BB GTs

### ISSUE THREAD

**Issue by geoseb94** [princeton-computational-imaging/SeeingThroughFog#22]
Hi,
Since 3D BB annotations are in camera coordinate system, could you please let me know how to get the corresponding yaw angle 
for the objects in the lidar frame? I would like to know if there is any alignment difference in the forward looking axis of camera and lidar, ie the constant angle that needs to be added to ''rotz' in annotations. Also, please let me know what 'orient3d' means in annotations?

Best regards,
George

**Comment by MarioBijelic** [comment]
Hi George, 

the orient3d matches the rotation_y angle from the KITTI dataset to enable an easy adaptation of the dataset to existing KITTI data pipelines. For the alignment of the axes you can check the calibration_tf_tree_full.json. It provides all extrinsic transformations.
