### ISSUE TITLE
Lidar to cam projections

### ISSUE THREAD

**Issue by manonthegithub** [princeton-computational-imaging/SeeingThroughFog#24]
Hello!

I am trying to project Lidar data onto the cam images, I have seen calibration files and your code on reading them, but it is still not that easy to understand on how should it work, the best I could make so far is this, but something is definitely missing :). The ones I got so far is this: 
![image](https://user-images.githubusercontent.com/10817016/102130171-cb0f1080-3e50-11eb-8f37-df168bfcf8b7.png)
![image](https://user-images.githubusercontent.com/10817016/102130196-d5c9a580-3e50-11eb-893e-3ee63c2891f7.png)

the right one seem to look like:
![image](https://user-images.githubusercontent.com/10817016/102130610-525c8400-3e51-11eb-960e-8d382883425f.png)

I am doing:

```python
scan = load_velodyne_scan(scan_path)
velodyne_to_camera, camera_to_velodyne, P, R, vtc, radar_to_camera, zero_to_camera = load_calib_data(calib_root, name_camera_calib, tftree)

ps = project_3d_to_2d(scan[:,:3].transpose(), vtc)

```
the first image I get is when I use `vtc` on "lidar_hdl64_strongest"
the second is when I use `vtc` on "lidar_vlp32_strongest", which seems much better, but still with some shift.

Can you please give some more details on how to make projection with the calibration you have?

Thank you a lot in advance!

**Comment by MartinHahner** [comment]
> The ones I got so far is this:
> ![image](https://user-images.githubusercontent.com/10817016/102130171-cb0f1080-3e50-11eb-8f37-df168bfcf8b7.png)
> ![image](https://user-images.githubusercontent.com/10817016/102130196-d5c9a580-3e50-11eb-893e-3ee63c2891f7.png)
> 
> the right one seem to look like:
> ![image](https://user-images.githubusercontent.com/10817016/102130610-525c8400-3e51-11eb-960e-8d382883425f.png)

Those links to the images do not work.

**Comment by manonthegithub** [comment]
@MartinHahner  strange, try reload the page, it works perfectly fine for me.

**Comment by manonthegithub** [comment]
Finally I have got a more or less good pictures, but seems that the points are still a bit shifted.
![image](https://user-images.githubusercontent.com/10817016/102236110-62c53b00-3ef3-11eb-9572-f19984da3c39.png)

Do you think it is the best we can get? or there is a possibility to align better?

**Comment by manonthegithub** [comment]
Sorry for the images, it was a bug in GitHub. 
Can you please check again?  
So what I have. This is the best I can get in projections from `lidar_hdl64_last` to `cam_stereo_left_lut`:
![me_1](https://user-images.githubusercontent.com/10817016/103034652-a5c38600-4565-11eb-9e0b-c5bdf165aab3.png)
![me_2](https://user-images.githubusercontent.com/10817016/103034691-c2f85480-4565-11eb-9f6b-adb30c2413b6.png)

Here is what you have in the dataset `lidar_hdl64_last_stereo_left`overlayed over `cam_stereo_left_lut `:
![orig](https://user-images.githubusercontent.com/10817016/103034784-f509b680-4565-11eb-8ad6-405b9c51f616.png)
![orig_img](https://user-images.githubusercontent.com/10817016/103035193-1cad4e80-4567-11eb-803b-fd08cf082ed4.png)

Seems like either I am taking a wrong camera or there is an error somewhere in calibration, as the projected liar points look a bit shifted to the left even in the original projections from the dataset. WDYT? What is the problem?

**Comment by manonthegithub** [comment]
@MartinHahner

**Comment by MartinHahner** [comment]
I don't see any major shift, the only thing I noticed is that on the left-hand side of the image it appears as if there is a tiny shift, but I think in general the calibration and your visualizations look fine of which areas are you referring to?

**Comment by manonthegithub** [comment]
@MartinHahner I have checked again, and yeah, looks like for a normal camera its fine. But for gated camera the shift looks significant (on the cyclist). I am using points from lidar_hdl64_strongest, gated images from gated1_rect and calib_gated_bwv.json as calibration for gated, maybe I should use a different folder for gated images, which one is right?

![1g](https://user-images.githubusercontent.com/10817016/104959592-dc5cb700-59d2-11eb-93aa-7fb28185bafc.png)

**Comment by MartinHahner** [comment]
Sorry @manonthegithub, I have not used this specific projection. 
Maybe one of the authors (e.g. @MarioBijelic) can help you.
I am just another user of this dataset.

**Comment by MarioBijelic** [comment]
Hi @manonthegithub, the provided point clouds are corrected relative to the camera time step. Hence, the point cloud has a misalignment relativ to the gated camera. To correct those measurements in a first step a file containing the time delays is given inside the DatasetViewer tool. Can try to filter gated captures with a larger time delay than 10ms?

**Comment by gokulesh-danapal** [comment]
Hi @manonthegithub, @MarioBijelic, @MartinHahner  I am trying to project radar points on RGB image coordinates. I use the load_calib_data function to get the radar_to_camera transformartion matrix. But multiplying it with both [x_cc, y_cc, 0, 1]T or [x_sc, y_sc, 0, 1]T doesnt give the correct results. I even tried using all three P,R and radar_to_camera matrices, but still no use. Could you please guide me as to what I am missing and what is the right way to do it?

**Comment by manonthegithub** [comment]
@MarioBijelic I have found a bug in load_calib_data which leaded to a shift on the projections to gated cam, submitting PR

**Comment by manonthegithub** [comment]
@MarioBijelic thanks for the comment about the timestamps, I will look into them also!

**Comment by manonthegithub** [comment]
@gokulesh-danapal you should use `vtc` as the final projection matrix (`P`), just multiply (matrix multiplication) the point cloud by it, and you will get the projected points (look at `def project_3d_to_2d(points3d, P)` in `visualisation.py`).

```
velodyne_to_camera, camera_to_velodyne, P, R, vtc, radar_to_camera, zero_to_camera = load_calib_data(calib_root, name_camera_calib, tftree)
    mat = vtc
```

hope this helps :). Best regards.

**Comment by MarioBijelic** [comment]
@manonthegithub Thank you for your for your fix. I merged it now.

**Comment by gokulesh-danapal** [comment]
@manonthegithub Can you tell me the transformation from Radar point cloud to Image? Thanks in advance

**Comment by manonthegithub** [comment]
@gokulesh-danapal no sure what you mean... I was speaking about this function:
https://github.com/princeton-computational-imaging/SeeingThroughFog/blob/094b95f64e1a1ed8a57e556984be16a8f8482cbc/tools/DatasetViewer/lib/visualization.py#L15

so you can just this one, pass `vtc` from my previous message as second parameter (`P`)

**Comment by gokulesh-danapal** [comment]
@manonthegithub Thanks for the reply. vtc is the transformation matrix to project lidar point cloud to camera image.  Similarly what is the transformation matrix for Radar point cloud to camera image?

**Comment by manonthegithub** [comment]
@gokulesh-danapal

ahh sorry I misunderstood. I didn't do Radar projection. Not sure what kind of data is in the Radar files, is it also 3d coordinates? Looking at how vtc is calculated:
https://github.com/princeton-computational-imaging/SeeingThroughFog/blob/094b95f64e1a1ed8a57e556984be16a8f8482cbc/tools/DatasetViewer/lib/read.py#L162

you may try `rtc = np.matmul(np.matmul(P, R), radar_to_camera)` and then pass etc to `project_3d_to2d`.

**Comment by gokulesh-danapal** [comment]
@manonthegithub 
Radar points are in dictionary format. I did the same method as you had mentioned above. But there are two sets of x,y coordiantes. I have attached image below. Not sure which (x,y) is correct. Any idea what sc and cc might mean?
![image](https://user-images.githubusercontent.com/55865102/116441186-84471380-a851-11eb-9110-7313762c94ad.png)

**Comment by gokulesh-danapal** [comment]
@manonthegithub  with x_sc and y_sc I get the first image and with x_cc and y_cc, I get the second image 
![image](https://user-images.githubusercontent.com/55865102/116441734-fe779800-a851-11eb-8a0d-1d6ee0fdecba.png)
![image](https://user-images.githubusercontent.com/55865102/116441760-06373c80-a852-11eb-84d9-51f3699ba45d.png)

**Comment by manonthegithub** [comment]
@gokulesh-danapal with that I cant help. Try looking for the radar model docs, maybe they have this info...

**Comment by gokulesh-danapal** [comment]
@manonthegithub Thanks

**Comment by SaketChaturvedi** [comment]
Hello @manonthegithub, @gokulesh-danapal, @MartinHahner, @MarioBijelic, 

I am trying to perform a Lidar point cloud projection on an image. I am performing the following steps:
1. scan = load_velodyne_scan(scan_path)
2. velodyne_to_camera, camera_to_velodyne, P, R, vtc, radar_to_camera, zero_to_camera = load_calib_data(calib_root, name_camera_calib, tftree)
3. ps = project_3d_to_2d(scan[:,:3].transpose(), vtc)

I can generate ps. Now, how can we convert ps to an image? I am using PIL for it, but I was not able to generate an image. Can anyone please help me with this? 

I really appreciate any help.

**Comment by MarioBijelic** [comment]
Hi @SaketChaturvedi @gokulesh-danapal, today I added projection code in ProjectionTools (Lidar2RGB, Radar2RGB) which should help to project lidar and radar data into the image frame.

**Comment by gokulesh-danapal** [comment]
> 
> 
> Hi @SaketChaturvedi @gokulesh-danapal, today I added projection code in ProjectionTools (Lidar2RGB, Radar2RGB) which should help to project lidar and radar data into the image frame.

Thank you. That helps a lot. Just a few questions. Would be great if you could answer them too.
1. Is the radar velocity compensated for ego motion?
2. Why arent rcs values available for all radar points?

**Comment by SaketChaturvedi** [comment]
Thank you, @MarioBijelic, for sharing codes.

**Comment by MarioBijelic** [comment]
Hi, 

your welcome. 
The data is egomotion corrected, but the rcs values are not available due to privacy reasons. Sorry!
