### ISSUE TITLE
Matching lidar strongest and last returns

### ISSUE THREAD

**Issue by ptoews** [princeton-computational-imaging/SeeingThroughFog#26]
Hi,

since the strongest and last returns are stored in different files with different counts of points per point cloud I'm having trouble matching them together, to find out e.g. what the corresponding last return is for a strongest return yielded by the same laser beam. Is it possible to somehow reconstruct this information? 
I converted the position data to polar coordinates but noticed the points are not evenly distributed, and a series of points might overlap with another one (see below), so matching them by polar angles similarity won't work properly either.

![image](https://user-images.githubusercontent.com/1062119/105069624-80516b80-5a82-11eb-9bc0-c75d15c92f45.png)

**Comment by MartinHahner** [comment]
That's a good question, I would also be interested to know the answer.

**Comment by MarioBijelic** [comment]
Hi, the uploaded point clouds are ego motion corrected. This can lead to uneven distributed points. Can you share how you compared the point clouds. I can continue from there and try to see whether we can provide you raw not egomotion corrected measurements for the comparisons.

**Comment by ptoews** [comment]
Thanks for the explanation.
I compared them by calculating the angles for each point and plotted them in angular space, as above, but colored by return type. I chose blue for strongest and orange for last returns, and configured 50% opacity so that overlapping points result in a redish color, here is a (somewhat extreme) example:

![image](https://user-images.githubusercontent.com/1062119/110606201-3afc1100-818a-11eb-8c27-b8897f25dd54.png)
As you can see there are both single strongest and last returns without a corresponding partner, but isn't the HDL64 supposed to return either only last or both?

Anyway, in the image it appears that it should be possible to match the points, however since I have to calculate the angles from XYZ values with limited precision the angular coordinates are not exactly equal. And since the distribution is so uneven choosing a threshold is difficult.

Just wondering, the raw data should contain information about the correspondences right?

**Comment by ptoews** [comment]
I've realized that many of those points can be eliminated a priori by comparing XYZ and checking if they are exactly equal. However the rest of my post should still hold. Here is the same point cloud but filtered:
![image](https://user-images.githubusercontent.com/1062119/111977875-8bb52780-8b03-11eb-98d3-81ac9998b993.png)
From 0 to ~120 degrees horizontal angle there are mostly single returns without a corresponding partner, whereas further to the right most points have overlapping other points, where the matching would still be the same problem.

Looking at the filtered version I also noticed that there are some kind of similarities of the single echos on the left, where strongest and last echos follow a similar pattern but the strongest points are further up and more disturbed. Could this also be related to the motion correction? Or maybe I'm just reading too much into this.

**Comment by MarioBijelic** [comment]
Hi ptoews, can you send me the example idx or name such that I can have a look at it? 

The lidar returns both the strongest and last return. Is this sample from a adverse weather set? I expect the ego motion to be different only for points, which are not identical. This for example happens in dense fog where the detection range for last returns is further. Can you find such artefacts only in some samples or across the whole dataset?

**Comment by ptoews** [comment]
I just checked a few more random samples and could see single strongest and last returns in all of them, even in absolutely clear conditions (e.g. `2019-09-11_16-39-41_01770`). Above diagrams were generated from file `2018-10-29_16-42-03_00560.bin`.

Here is another example from file `2018-02-12_07-16-32_00100.bin` where the two returns are very similarly offset to each other:
![image](https://user-images.githubusercontent.com/1062119/113107612-6c558300-9204-11eb-8f9e-a018b39ba6fe.png)

**Comment by MarioBijelic** [comment]
Hi ptoews, 

Sorry for the delayed answer. I was able to reproduce your observations. But those misalignments are also visible in the raw data without egomotion correction. Hence, I added also a script for projecting raw lidar data and matching strongest and last echos to help others pick up. Currently, it uses a scipy.spatial.KDTree to lookup closest neighbours. To constrain the results it applies sensor constrains as forcing to have same ring and Laser Power Echo last < Laser Power Strongest.

**Comment by OuYaozhong** [comment]
Hi, @MarioBijelic 

I also notice this problem.

I found that, not only the angle is mismatched, but also the number of point between the strongest and last `.bin` file with the same file name.

🌟I wonder how the VELODYNE sensor output when using the dual-echo mode, leading to this kind of problem ?

- Both of the echo are mixed together, making the users under to separate them, just receive a point cloud with approximately double number of points ? And you separate them based on the program written by yourself ?

- Or the resulted point cloud can be separated into strongest and last one, with some index given by the sensor driver ? Just unable to guarantee that the number of points, the angle of points, the amplitude of intensity are the same between two echoes ?

👋 I also have do some statistic about this, and if necessary, I can provide some picture about the statistic data.

🌟Meanwhile, I can not find the program that you mentioned.

> Hence, I added also a script for projecting raw lidar data and matching strongest and last echos to help others pick up. 

Thanks in advance.

Best Regards
