### ISSUE TITLE
Can't download the dataset

### ISSUE THREAD

**Issue by Icecream-blue-sky** [princeton-computational-imaging/SeeingThroughFog#27]
Hi,
after registration at https://www.uni-ulm.de/en/in/driveu/projects/dense-datasets, I got an download url  in my mailbox. However, I can't download it. It reminded me that the file had been deleted or expired. Maybe you should check it. Thanks!

**Comment by Icecream-blue-sky** [comment]
The author told me that the dataset is being updated. And it will return to normal within a week. Hopes to help somebody have the same problems as me!

**Comment by veesohoni** [comment]
Hello, 

Yes, I am facing the same issue for the past two weeks. I hoped today it should work But I am getting the same message.
Can anyone post the updates about this?

**Comment by MarioBijelic** [comment]
Hi, 

I double checked, but I am able to register and download the dataset currently. Do you have more hints on your issue? 
What is the message, which is being shown?
Nonetheless, the dataset the links are regularly replaced causing sometimes 1-2 days of downtime. Sorry for the inconvenience.
