### ISSUE TITLE
Question of supplemenent document

### ISSUE THREAD

**Issue by Youngsplace0913** [princeton-computational-imaging/SeeingThroughFog#29]
![image](https://user-images.githubusercontent.com/78135656/109511807-c6b8d200-7ae6-11eb-8e61-a976e7af49af.png)

First of all, I was impressed by the great research.
I would like to implement and use these models myself, but I do not know how to do it.

Did you label the fog point separately by making such an image?
I'd like to hear a specific explanation.

Also, what should I do if I want to use those models?
In addition, I wonder if LiDAR-Only SSD used 2D Detector or 3D Detector. If there is a ref code, can you tell me?

I'll wait for your answer. Thank you in advance.

**Comment by MartinHahner** [comment]
@Youngsplace0913: Where did you find this image? I can't find it in the supplementary materials.
