### ISSUE TITLE
Dense Dataset Link not working since few days

### ISSUE THREAD

**Issue by veesohoni** [princeton-computational-imaging/SeeingThroughFog#30]
Hello, 

I am watching the Cloudstore Space for Dense Data, I am working on Seeing through Fog, and it seems from last week it is not accessible. Could you please confirm!

**Comment by connorlee77** [comment]
@veesohoni have you successfully downloaded the set? The download speeds are extremely slow for me (< 1mbps). Wondering if you ran into the same issue.
