### ISSUE TITLE
Specific data folders used for training and validation + Slow download speed

### ISSUE THREAD

**Issue by connorlee77** [princeton-computational-imaging/SeeingThroughFog#31]
I was wondering which specific folders (cam_stereo_left, gated0_raw, etc...) contain the RGB, LIDAR, Gated, and Radar training/validation data in the paper. The overall download size is very large and the download speed is very slow, so I would like to avoid downloading irrelevant data. 

 Is there any README file or documentation describing what I'm asking?

Also, my download speed is roughly 1500 KB/s. Total download time for SeeingThroughFogCompressed.zip is projected to be a couple days. Is this to be expected? I'm downloading from the US west coast. Is there any quicker way to get the data?

**Comment by MarioBijelic** [comment]
Hi,

I checked my download speed and I am reaching 5-6mb/s. We will look into this in more detail.
For now you can use following folders cam_stereo_left, lidar_hdl_last_stereo (Projected Depth into image), gated0_rect, gated1_rect, gated2_rect and radar_targets.

**Comment by jmiemirza** [comment]
Hi,

Similar question. Struggling a little here. So as far as I can see: 

'cam_stereo_left' contains the rgb images
'gt_labels' contains the ground truth labels

Still struggling to find .bin files for lidar sweeps? Does this dataset provide that? 

Also, calibration files like KITTI and Ground Planes? Is there a way to get them?

**Comment by connorlee77** [comment]
I think the lidar sweeps are in lidar_hdl64_strongest. No idea about calibration files.

**Comment by MartinHahner** [comment]
That is the KITTI calibration file I created from `calib_tf_tree_full.json`: [calib_in_kitti_format_R_identity.txt](https://github.com/princeton-computational-imaging/SeeingThroughFog/files/6211205/calib_in_kitti_format_R_identity.txt)

These are the folders containing lidar sweeps:

lidar_hdl64_last
lidar_hdl64_strongest

lidar_vlp32_last
lidar_vlp32_strongest

**Comment by jmiemirza** [comment]
Many thanks! Might just work :)

**Comment by MarioBijelic** [comment]
Hi @jmiemirza, I have added velodyne ground planes similar to Kitti to the velodyne_planes folder.
