### ISSUE TITLE
Reading Cam Labels 

### ISSUE THREAD

**Issue by veesohoni** [princeton-computational-imaging/SeeingThroughFog#32]
Hello, 

I am referring to label files from: cam_left_labels_TMP/

It would be helpful if I get the information about what these labels denote and how to read this file.

![Issue_Labels](https://user-images.githubusercontent.com/62149326/111175924-43d05680-857f-11eb-9be0-2f583dc9d04b.JPG)

**Comment by MartinHahner** [comment]
Have a look here:
https://github.com/princeton-computational-imaging/SeeingThroughFog/blob/master/tools/DatasetViewer/lib/read.py#L24-L51

**Comment by veesohoni** [comment]
Thank you Martin!
