### ISSUE TITLE
Converting to KITTI format

### ISSUE THREAD

**Issue by deeptibhegde** [princeton-computational-imaging/SeeingThroughFog#33]
Hi,
If I would like to generate the calib files for each sample like in KITTI,:

`P0: 7.070493000000e+02 0.000000000000e+00 6.040814000000e+02 0.000000000000e+00 0.000000000000e+00 7.070493000000e+02 1.805066000000e+02 0.000000000000e+00 0.000000000000e+00 0.000000000000e+00 1.000000000000e+00 0.000000000000e+00`

`P1: 7.070493000000e+02 0.000000000000e+00 6.040814000000e+02 -3.797842000000e+02 0.000000000000e+00 7.070493000000e+02 1.805066000000e+02 0.000000000000e+00 0.000000000000e+00 0.000000000000e+00 1.000000000000e+00 0.000000000000e+00`

`P2: 7.070493000000e+02 0.000000000000e+00 6.040814000000e+02 4.575831000000e+01 0.000000000000e+00 7.070493000000e+02 1.805066000000e+02 -3.454157000000e-01 0.000000000000e+00 0.000000000000e+00 1.000000000000e+00 4.981016000000e-03`

`P3: 7.070493000000e+02 0.000000000000e+00 6.040814000000e+02 -3.341081000000e+02 0.000000000000e+00 7.070493000000e+02 1.805066000000e+02 2.330660000000e+00 0.000000000000e+00 0.000000000000e+00 1.000000000000e+00 3.201153000000e-03`

`R0_rect: 9.999128000000e-01 1.009263000000e-02 -8.511932000000e-03 -1.012729000000e-02 9.999406000000e-01 -4.037671000000e-03 8.470675000000e-03 4.123522000000e-03 9.999556000000e-01`

`Tr_velo_to_cam: 6.927964000000e-03 -9.999722000000e-01 -2.757829000000e-03 -2.457729000000e-02 -1.162982000000e-03 2.749836000000e-03 -9.999955000000e-01 -6.127237000000e-02 9.999753000000e-01 6.931141000000e-03 -1.143899000000e-03 -3.321029000000e-01`

`Tr_imu_to_velo: 9.999976000000e-01 7.553071000000e-04 -2.035826000000e-03 -8.086759000000e-01 -7.854027000000e-04 9.998898000000e-01 -1.482298000000e-02 3.195559000000e-01 2.024406000000e-03 1.482454000000e-02 9.998881000000e-01 -7.997231000000e-01`

would I have to use the functions in DataViewerV2.py to generate these values?  Does the ` camera_to_velodyne` returned by the `load_calib_data` function correspond to `Tr_imu_to_velo`? 

If I am only using the lidar files from **lidar_hdl4_last_stereo_left** will I be able to iterate over the files and have a corresponding camera calib file and tf tree? 

Also, is there a reason some lidar files are `.npz` and some are `.bin`?

Thank you for the dataset!

**Comment by deeptibhegde** [comment]
Ah I see that  lidar_hdl4_last_stereo_left has the projected files. Which folder contains the pointcloud bin files?

**Comment by jmiemirza** [comment]
lidar_hdl64_strongest and lidar_hdl64_last contains the .bin files.
