### ISSUE TITLE
Training SSD Model

### ISSUE THREAD

**Issue by ghost** [princeton-computational-imaging/SeeingThroughFog#37]
Hello,

I am very impressed by your work in the SeeingThroughFog paper. I am working on training an SSD model using only Camera Stereo Images to learn from your work. I have found 14 different classes in the dataset ('LargeVehicle', 'PassengerCar_is_group', 'RidableVehicle', 'Pedestrian', 'Pedestrian_is_group', 'PassengerCar', 'Vehicle', 'Obstacle', 'RidableVehicle_is_group', 'Vehicle_is_group', 'LargeVehicle_is_group', 'DontCare', 'train', 'person'). I was trying to understand the label classes, but I have few questions. How many classes have you used for training? What is the difference between label class 'PassengerCar' and 'Vehicle'? What does the label 'Vehicle_is_group' exactly mean? 

Also, while generating TFRecord files for Lidar and Radar data, did you gave input as a projected 2D image?  

Thank you very much. Looking forward to hearing from you back!

**Comment by connorlee77** [comment]
@MarioBijelic for the paper, did you guys coalesce the 14 labels shown above into the ones listed in the supplementary material: Pedestrian, Truck, Car, Cyclist, and DontCare?
