### ISSUE TITLE
Lidar Data Format and Foggification Parameters for VLP32 Lidar

### ISSUE THREAD

**Issue by qiank10** [princeton-computational-imaging/SeeingThroughFog#4]
Hello, 

I download some HDL64 and VLP32 Lidar data from the DENSE datasets. Each data file consists of 5 columns where the first 3 columns are x/y/z coordinates and the 4th column is intensity. What is the meaning of the 5th column? 

I have a VLP32 Lidar and would like to apply fortification to its data frames. Have you measured the parameters g and n for VLP32 Lidar? If not, is it possible to derive them from the matching data frames of HDL64 and VLP32 Lidar and the known parameters of the HDL64 Lidar?

Thank you and looking forward to your reply.

**Comment by MarioBijelic** [comment]
Hi @qiank10, the fifth colum contains the laser power level. Velodyne sensors are able to adaptively set the laser power level dependent on the target to prevent saturation of the detector for high reflective targets and to increase laser power for low reflective targets. 

In terms of Foggification. We did not measure the parameters for the VLP32, but there is a follow up paper “CNN-based Lidar Point Cloud De-Noising in Adverse Weather” written by Heizler et. al. using our algorithm for the VLP32 and the same parameters n/g as for the HDL64S3D.

**Comment by qiank10** [comment]
Thank you for the answers. I'll try the parameters n/g for the HDL64S3D.

**Comment by ptoews** [comment]
> Hi @qiank10, the fifth colum contains the laser power level. Velodyne sensors are able to adaptively set the laser power level dependent on the target to prevent saturation of the detector for high reflective targets and to increase laser power for low reflective targets.

@MarioBijelic Follow-up question to your answer: The fifth column ranges from 0-63 for the HDL64 S3 and 0-31 for the VLP32, however the manual of the HDL64 states that in automatic power mode the returned power-level is a 3-bit information, which therefore ranges only from 0-7. Based on the value ranges I assumed this column describes the vertical index of the emitting laser, or am I confusing something here?

**Comment by MartinHahner** [comment]
@ptoews You are right, the 5th feature is the **_LiDAR channel_** and not the _laser power level_.

**Comment by ptoews** [comment]
Hey @MartinHahner, thanks for your answer. Can you elaborate what you mean by lidar channel? By vertical index I mean the association to one of the 32 or 64 vertically mounted lasers, I think you are referring to the same? And may I ask how you found this out or possibly have a source for that? That would help me so that I can rely on that in my thesis. Thanks!

**Comment by MartinHahner** [comment]
@ptoews Yes, I mean the same as you. It already becomes obvious when you look at the value range as you pointed out.
But I also extended their dataset viewer in such a way that I can color-code the points based on the 5th feature. 
So I am absolutely certain that this is the **_LiDAR channel_** and not the _laser power level_.

When you visualize the data with their [dataset viewer](https://github.com/princeton-computational-imaging/SeeingThroughFog/blob/master/tools/DatasetViewer/DataViewer_V2.py), you can add a few lines of code within **update_lidar3d** to mask out points based on the 5th column, to verify it for yourself if you like.

https://github.com/princeton-computational-imaging/SeeingThroughFog/blob/fae362911d03f01e6bc672b532b90d486df8d166/tools/DatasetViewer/DataViewer_V2.py#L386-L438

**Comment by ptoews** [comment]
Thanks for the tip, will definitely do that!
