### ISSUE TITLE
labels, 27th element

### ISSUE THREAD

**Issue by connorlee77** [princeton-computational-imaging/SeeingThroughFog#40]
read.py only retrieves up to the 26th element of the labels (i.e 'visibleLidar': kitti_properties[25] ). What is the 27th element supposed to be (kitti_properties[26])? visibleRadar?

**Comment by MarioBijelic** [comment]
Dear @connorlee77, 

yes the 26th value is visibleRadar. The values can be 'True', 'False' and -1. -1 always occurs if no information was provided by the annotator. But as you pointed out there is a bug in the read.py function. The labels should not always be True. The intention of inventing the labels visible<Sensor> was to know in which sensor stream the object can be seen with the annotators eyes.

**Comment by connorlee77** [comment]
gotcha, thanks!

**Comment by connorlee77** [comment]
@MarioBijelic Question for on definition of visibility: does visibility mean the object is in the sensor field of view, but not visible to human eyes or does it mean it is out of the sensor field of view?
