### ISSUE TITLE
Cannot Download Dataset

### ISSUE THREAD

**Issue by yuanziii** [princeton-computational-imaging/SeeingThroughFog#41]
Hi, thanks for your impressive work! The dataset is so well-collected with novel preprocessing tools developed.

I would like to use the dataset in my research work, but I registered and it said the download link will be sent to my email. But I did not received any link or email. I have also checked the junk box so it is not missed. Is there any problems? Thanks.

Btw, if the network mentioned in the paper "Seeing through Fog" can be released, it would be even more helpful for our to follow your work.

Looking forward to your reply, thanks

**Comment by MarioBijelic** [comment]
Dear @yuanziii, 

I checked the link, it is still online and running. Can you try a different mailing address?
