### ISSUE TITLE
Which dataset is used to evaluate the work?

### ISSUE THREAD

**Issue by chengricky** [princeton-computational-imaging/SeeingThroughFog#46]
Hi, many thanks for your great work!

As for the quatitative detection AP listed in your paper, which dataset is used? The daytime split, night split or both of them?
And in the training stage, both the daytime and the night data are used?

THX.

**Comment by MarioBijelic** [comment]
Hi @chengricky, 

we used both day and night splits for training and evaluation. 

Best, 
Mario
