### ISSUE TITLE
Using Friction Data

### ISSUE THREAD

**Issue by hasirk** [princeton-computational-imaging/SeeingThroughFog#48]
@MarioBijelic 
First of all thank you for the dataset in adverse weather. I am planning to make use of the friction data provided in the dataset, however is there a way to map the friction data with location or GPS data ? 
Also I assume that the friction data corresponds to the friction values under vehicle and time synchronized with the image and velodyne data under the same name.

**Comment by MarioBijelic** [comment]
Hi @hasirk, 

yes exactly the friction data is measured underneath the vehicle and synchronised to other sensor data. 
GPS data is currently not available due to privacy reasons.
