### ISSUE TITLE
errors while unzipping files in FogchamberDataset and SeeingThroughFogCompressed

### ISSUE THREAD

**Issue by MartinHahner** [princeton-computational-imaging/SeeingThroughFog#5]
Hi, 
unfortunately, I can not successfully unzip the files within `FogchamberDataset` and `SeeingThroughFogCompressed`.

To make sure that the download was not corrupted on my side, I already downloaded `FogchamberDataset.zip` and `SeeingThroughFogCompressed.zip` multiple times from your server.

While unzipping `FogchamberDataset.zip` and `SeeingThroughFogCompressed.zip` itself works fine, 
unzipping the files within it's extracted subfolders doesn't work.

When trying to unzip those, I get the following message for the archives in `FogchamberDataset`:
```bash
4 archives were successfully processed.
7 archives had fatal errors.
```

and this for the archives in `SeeingThroughFogCompressed`:
```bash
10 archives were successfully processed.
1 archive had warnings but no fatal errors.
32 archives had fatal errors.
```

I think you should be able to reproduce a "fatal error" e.g. when you do 
`unzip lidar_hdl64_strongest.zip` in `FogchamberDataset/lidar_hdl64_strongest`.

<img width="396" alt="grafik" src="https://user-images.githubusercontent.com/14181188/89998780-4471d900-dc8e-11ea-9801-60246b9533d1.png">

This is the trace I get:
```bash
Archive:  lidar_hdl64_strongest.zip
warning [lidar_hdl64_strongest.zip]:  zipfile claims to be last disk of a multi-part archive;
  attempting to process anyway, assuming all parts have been concatenated
  together in order.  Expect "errors" and warnings...true multi-part support
  doesn't exist yet (coming soon).
file #1:  bad zipfile offset (local header sig):  4
file #2:  bad zipfile offset (local header sig):  84
file #3:  bad zipfile offset (local header sig):  1292455
file #4:  bad zipfile offset (local header sig):  2585819
file #5:  bad zipfile offset (local header sig):  3877631
file #6:  bad zipfile offset (local header sig):  5169771
file #7:  bad zipfile offset (local header sig):  6462841
file #8:  bad zipfile offset (local header sig):  7755507
file #9:  bad zipfile offset (local header sig):  9046452
file #10:  bad zipfile offset (local header sig):  10341663
file #11:  bad zipfile offset (local header sig):  11633918
file #12:  bad zipfile offset (local header sig):  12929252
file #13:  bad zipfile offset (local header sig):  14225869
file #14:  bad zipfile offset (local header sig):  15518351
file #15:  bad zipfile offset (local header sig):  16816588
file #16:  bad zipfile offset (local header sig):  18111883
file #17:  bad zipfile offset (local header sig):  19405226
file #18:  bad zipfile offset (local header sig):  20698401
file #19:  bad zipfile offset (local header sig):  21990109
file #20:  bad zipfile offset (local header sig):  23281287
file #21:  bad zipfile offset (local header sig):  24574933
file #22:  bad zipfile offset (local header sig):  25868771
file #23:  bad zipfile offset (local header sig):  27161983
file #24:  bad zipfile offset (local header sig):  28453010
file #25:  bad zipfile offset (local header sig):  29745940
file #26:  bad zipfile offset (local header sig):  31039964
file #27:  bad zipfile offset (local header sig):  32334045
file #28:  bad zipfile offset (local header sig):  33629028
file #29:  bad zipfile offset (local header sig):  34923028
file #30:  bad zipfile offset (local header sig):  36218481
file #31:  bad zipfile offset (local header sig):  37512234
file #32:  bad zipfile offset (local header sig):  38810796
file #33:  bad zipfile offset (local header sig):  40106979
file #34:  bad zipfile offset (local header sig):  41401521
file #35:  bad zipfile offset (local header sig):  42699155
file #36:  bad zipfile offset (local header sig):  43992782
file #37:  bad zipfile offset (local header sig):  45287246
file #38:  bad zipfile offset (local header sig):  46581336
file #39:  bad zipfile offset (local header sig):  47873381
file #40:  bad zipfile offset (local header sig):  49170729
file #41:  bad zipfile offset (local header sig):  50466394
file #42:  bad zipfile offset (local header sig):  51766117
file #43:  bad zipfile offset (local header sig):  53062799
file #44:  bad zipfile offset (local header sig):  54360313
file #45:  bad zipfile offset (local header sig):  55654613
file #46:  bad zipfile offset (local header sig):  56949106
file #47:  bad zipfile offset (local header sig):  58244705
file #48:  bad zipfile offset (local header sig):  59539629
file #49:  bad zipfile offset (local header sig):  60835290
file #50:  bad zipfile offset (local header sig):  62129307
file #51:  bad zipfile offset (local header sig):  63422834
file #52:  bad zipfile offset (local header sig):  64718391
file #53:  bad zipfile offset (local header sig):  66013988
file #54:  bad zipfile offset (local header sig):  67311345
file #55:  bad zipfile offset (local header sig):  68606532
file #56:  bad zipfile offset (local header sig):  69899595
file #57:  bad zipfile offset (local header sig):  71192095
file #58:  bad zipfile offset (local header sig):  72485408
file #59:  bad zipfile offset (local header sig):  73781890
file #60:  bad zipfile offset (local header sig):  75075232
file #61:  bad zipfile offset (local header sig):  76376460
file #62:  bad zipfile offset (local header sig):  77671315
file #63:  bad zipfile offset (local header sig):  78964356
file #64:  bad zipfile offset (local header sig):  80256813
file #65:  bad zipfile offset (local header sig):  81549048
file #66:  bad zipfile offset (local header sig):  82844999
file #67:  bad zipfile offset (local header sig):  84137137
file #68:  bad zipfile offset (local header sig):  85437263
file #69:  bad zipfile offset (local header sig):  86731938
file #70:  bad zipfile offset (local header sig):  88028050
file #71:  bad zipfile offset (local header sig):  89325220
file #72:  bad zipfile offset (local header sig):  90617851
file #73:  bad zipfile offset (local header sig):  91915628
file #74:  bad zipfile offset (local header sig):  93210948
file #75:  bad zipfile offset (local header sig):  94503290
file #76:  bad zipfile offset (local header sig):  95796339
file #77:  bad zipfile offset (local header sig):  97087997
file #78:  bad zipfile offset (local header sig):  98383722
file #79:  bad zipfile offset (local header sig):  99678481
file #80:  bad zipfile offset (local header sig):  100973162
file #81:  bad zipfile offset (local header sig):  102270798
file #82:  bad zipfile offset (local header sig):  103566676
file #83:  bad zipfile offset (local header sig):  104860820
file #84:  bad zipfile offset (local header sig):  106155307
file #85:  bad zipfile offset (local header sig):  107451449
file #86:  bad zipfile offset (local header sig):  108749420
file #87:  bad zipfile offset (local header sig):  110054951
file #88:  bad zipfile offset (local header sig):  111346346
file #89:  bad zipfile offset (local header sig):  112641992
file #90:  bad zipfile offset (local header sig):  113894838
file #91:  bad zipfile offset (local header sig):  115147796
file #92:  bad zipfile offset (local header sig):  116399960
file #93:  bad zipfile offset (local header sig):  117654099
file #94:  bad zipfile offset (local header sig):  118910916
file #95:  bad zipfile offset (local header sig):  120168276
file #96:  bad zipfile offset (local header sig):  121429930
file #97:  bad zipfile offset (local header sig):  122694434
file #98:  bad zipfile offset (local header sig):  123955740
file #99:  bad zipfile offset (local header sig):  125219836
file #100:  bad zipfile offset (local header sig):  126479615
file #101:  bad zipfile offset (local header sig):  127734190
file #102:  bad zipfile offset (local header sig):  128988789
file #103:  bad zipfile offset (local header sig):  130241864
file #104:  bad zipfile offset (local header sig):  131497036
file #105:  bad zipfile offset (local header sig):  132754659
file #106:  bad zipfile offset (local header sig):  134011773
file #107:  bad zipfile offset (local header sig):  135268425
file #108:  bad zipfile offset (local header sig):  136526702
file #109:  bad zipfile offset (local header sig):  137790606
file #110:  bad zipfile offset (local header sig):  139056533
file #111:  bad zipfile offset (local header sig):  140327818
file #112:  bad zipfile offset (local header sig):  141598340
file #113:  bad zipfile offset (local header sig):  142868462
file #114:  bad zipfile offset (local header sig):  144135196
file #115:  bad zipfile offset (local header sig):  145403230
file #116:  bad zipfile offset (local header sig):  146680238
error: invalid zip file with overlapped components (possible zip bomb)
```

This is my setup:
```bash
$ hostnamectl

  Operating System: Debian GNU/Linux 9 (stretch)
            Kernel: Linux 4.9.0-13-amd64
      Architecture: x86-64

$ unzip --version

UnZip 6.00 of 20 April 2009, by Debian. Original by Info-ZIP.
```

**Comment by flkraus** [comment]
I think you are getting those errors because of the split zip files (.z01, .z02, ...).

Try something like:
`$ zip -FF lidar_hdl64_strongest.zip --out full_lidar_hdl64_strongest.zip`
`$ unzip full_lidar_hdl64_strongest.zip`

See also:
https://askubuntu.com/questions/31298/how-to-extract-and-join-files-xxx-zip-xxx-z01-and-xxx-z02
https://support.firmex.com/hc/en-us/articles/204579673-Downloads-with-multiple-parts-z01-and-z02-files-

**Comment by MartinHahner** [comment]
Hi Florian, 
thanks for getting back to me so quickly.

> I think you are getting those errors because of the split zip files (.z01, .z02, ...).
>
> Try something like:
> `$ zip -FF lidar_hdl64_strongest.zip --out full_lidar_hdl64_strongest.zip`
> `$ unzip full_lidar_hdl64_strongest.zip`
> 
> See also:
> https://askubuntu.com/questions/31298/how-to-extract-and-join-files-xxx-zip-xxx-z01-and-xxx-z02
> https://support.firmex.com/hc/en-us/articles/204579673-Downloads-with-multiple-parts-z01-and-z02-files-

You were right, the two commands you mentioned work.

I thought of this as well, but then I thought that can't be it 
because some of the multi-part files like `cam_stereo_left.zip` succeeded without concatenating the multiple parts beforehand. 

While this should fix the errors,  
it still makes it quite cumbersome to get the whole dataset ready
(because of its many subfolders and multi-part `.zip` files therein).

Anyways, thanks for your help, I am looking forward to play with your data once I fully unpacked it. 🙂

**Comment by flkraus** [comment]
Hi Martin,

you're welcome. I don't know how to unpack all the data automatically from the terminal (maybe a short python script could work). However I tried to use 7zip, which can handle multipart zip files (although I only tried this on windows).

Regarding the `cam_stereo_left.zip` I think you should check if you unpacked everything, since I could unpack `lidar_hdl64_strongest.zip` with `unzip`, but it only unpacked the data from the actual `.zip` file and not from the `.zXX` files.

**Comment by MartinHahner** [comment]
OK, thanks for letting me know. I will unpack everything again using the method you described above.
And a little python script may really be the way to go here. 
Once I am done, I will share it here.

**Comment by MartinHahner** [comment]
You were right again, beforehand only **483** files were extracted via `unzip cam_stereo_left.zip` 
(which is probably the content of the last file in the multi-part sequence).

`7zip` seems to also work accordingly on Linux, so thanks for the hint.
```bash
$ 7z e cam_stereo_left.zip

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,12 CPUs Intel(R) Core(TM) i7-8086K CPU @ 4.00GHz (906EA),ASM,AES-NI)

Scanning the drive for archives:
1 file, 1433542002 bytes (1368 MiB)

Extracting archive: cam_stereo_left.zip
--
Path = cam_stereo_left.zip
Type = zip
Physical Size = 1433542002
Embedded Stub Size = 4
64-bit = +
Total Physical Size = 4579270002
Multivolume = +
Volume Index = 2
Volumes = 3

Everything is Ok

Folders: 1
Files: 1500
Size:       4729942338
Compressed: 4579270002
```
`7zip` detects **3** volumes and extracts **1500** files.

**Comment by MartinHahner** [comment]
```bash
# move all files out of their subfolders
find . -mindepth 2 -type f -print -exec mv {} . \;

# remove all folders but not files
rm -r */

# unzip all multi-part files via 7zip
7z x "*.zip"
```

Running this in `.../FogchamberDataset/` and `.../SeeingThroughFogCompressed/` now did the trick for me.

**Comment by MartinHahner** [comment]
After starting the commands mentioned above last night, I found this message this morning for `SeeingThroughFogCompressed`:
```bash
77% 7325 - cam_stereo_left_raw_history_-2/2018-12-13_10-36-07_00000.tiff
terminate called after throwing an instance of 'CInBufferException'
Aborted
```

Now there seems to remain a problem in `SeeingThroughFogCompressed/cam_stereo_left_raw_history_-2`

```bash
$ 7z x cam_stereo_left_raw_history_-2.zip

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,12 CPUs Intel(R) Core(TM) i7-8086K CPU @ 4.00GHz (906EA),ASM,AES-NI)

Scanning the drive for archives:
1 file, 1006863131 bytes (961 MiB)

Extracting archive: cam_stereo_left_raw_history_-2.zip

ERRORS:
Missing volume : cam_stereo_left_raw_history_-2.z15

--
Path = cam_stereo_left_raw_history_-2.zip
Type = zip
ERROR = Missing volume : cam_stereo_left_raw_history_-2.z15
Physical Size = 1006863131
Embedded Stub Size = 4
64-bit = +
Total Physical Size = 37182735131
Multivolume = +
Volume Index = 24
Volumes = 25
```

`cam_stereo_left_raw_history_-2.z15` is missing, even on the server:

<img width="426" alt="grafik" src="https://user-images.githubusercontent.com/14181188/90132521-4d39dc00-dd6e-11ea-96f2-c59ee2e8f31c.png">

**Comment by MartinHahner** [comment]
> ```shell
> # move all files out of their subfolders
> find . -mindepth 2 -type f -print -exec mv {} . \;
> 
> # remove all folders but not files
> rm -r */
> 
> # unzip all multi-part files via 7zip
> 7z x "*.zip"
> ```
> 
> Running this in `.../FogchamberDataset/` and `.../SeeingThroughFogCompressed/` now did the trick for me.

For the `FogchamberDataset` part, those commands worked fine.

**Comment by flkraus** [comment]
Thanks for sharing your code snippets and insights! The missing `.z15` is a problem. I will see what we can do about that.

**Comment by MartinHahner** [comment]
> Thanks for sharing your code snippets and insights! The missing `.z15` is a problem. I will see what we can do about that.

No problem, same in `cam_stereo_left_raw_history_-5`.

There also `cam_stereo_left_raw_history_-5.z15` is missing.

**Comment by MartinHahner** [comment]
Unfortunately, I found more missing files:

`cam_stereo_left_raw_history_1.z[01-04]`
<img width="448" alt="grafik" src="https://user-images.githubusercontent.com/14181188/90169203-93a72f00-dd9e-11ea-8732-fa6271b1a43d.png">

`cam_stereo_left_raw_history_2.z01`
<img width="430" alt="grafik" src="https://user-images.githubusercontent.com/14181188/90169436-dbc65180-dd9e-11ea-8603-e711238653f6.png">

`cam_stereo_left_raw_history_3.z19`
<img width="321" alt="grafik" src="https://user-images.githubusercontent.com/14181188/90169679-3c558e80-dd9f-11ea-8f72-c313aa607908.png">

`gated1_raw.z02`
<img width="361" alt="grafik" src="https://user-images.githubusercontent.com/14181188/90170280-18467d00-dda0-11ea-8629-bc123bfcd7e0.png">

I hope I spotted every missing file.

**Comment by MartinHahner** [comment]
All missing files have been added. 👍

**Comment by connorlee77** [comment]
@MartinHahner did you find a clean way to extract all the files?

**Comment by MartinHahner** [comment]
> ```shell
> # move all files out of their subfolders
> find . -mindepth 2 -type f -print -exec mv {} . \;
> 
> # remove all folders but not files
> rm -r */
> 
> # unzip all multi-part files via 7zip
> 7z x "*.zip"
> ```
> 
> Running this in `.../FogchamberDataset/` and `.../SeeingThroughFogCompressed/` now did the trick for me.

I think this worked for me in the end.

**Comment by connorlee77** [comment]
Sweet, thanks a lot for the help!!

**Comment by ShengyuH** [comment]
Thanks Martin!
