### ISSUE TITLE
SeeingThroughFogData/cam_stereo_left 

### ISSUE THREAD

**Issue by acpl00** [princeton-computational-imaging/SeeingThroughFog#53]
Dear people,

Thank you for the nice project and sharing the dataset.

I am trying to load the Dense dataset for a sensor fusion project. However, 

According to this [website](https://github.com/princeton-computational-imaging/SeeingThroughFog)  The data shall be under 

SeeingThroughFogData
    |-- cam_stereo_left

But I can not find any data.

How can I load the following data:

|-- SeeingThroughFogData
    |-- cam_stereo_left
        |-- *.tiff
        |-- ...
    |-- cam_stereo_left_lut
        |-- *.png
        |-- ...
    |-- lidar_hdl64_last
        |-- *.bin
        |-- ...
    |-- lidar_hdl64_strongest
        |-- *.bin
        |-- ...
    |-- ...

Regards, and thank you

**Comment by MartinHahner** [comment]
see https://github.com/princeton-computational-imaging/SeeingThroughFog/issues/52#issuecomment-1034054192

**Comment by acpl00** [comment]
OK thank you for the replay, 

I will try in a few days


Ragards
