### ISSUE TITLE
Which RGB file did you use to train SSD?

### ISSUE THREAD

**Issue by Baboom-l** [princeton-computational-imaging/SeeingThroughFog#54]
I'm not sure which images uesd for object detection are from the cam_stereo_left file or the cam_stereo_left_lut file？

**Comment by hy3121** [comment]
Should this programme run on Ubuntu System?

**Comment by MarioBijelic** [comment]
Sorry, for the really late response. The cam_stereo_left_lut images are color mapped for labelling. For training the cam_stereo_left folder was using the code in https://github.com/princeton-computational-imaging/SeeingThroughFog/blob/master/tools/Raw2LUTImages/conversion_lib/process.py#L132

Best, Mario
