### ISSUE TITLE
How to decompress  SeeingThroughFogCompressed

### ISSUE THREAD

**Issue by Baboom-l** [princeton-computational-imaging/SeeingThroughFog#55]
I have downloaded the files 01 to 18, how should I unpack them？

My file directory is as follows：
SeeingThroughFogCompressed.z01  SeeingThroughFogCompressed.z08  SeeingThroughFogCompressed.z15
SeeingThroughFogCompressed.z02  SeeingThroughFogCompressed.z09  SeeingThroughFogCompressed.z16
SeeingThroughFogCompressed.z03  SeeingThroughFogCompressed.z10  SeeingThroughFogCompressed.z17
SeeingThroughFogCompressed.z04  SeeingThroughFogCompressed.z11  SeeingThroughFogCompressed.z18
SeeingThroughFogCompressed.z05  SeeingThroughFogCompressed.z12  SeeingThroughFogCompressed.zip
SeeingThroughFogCompressed.z06  SeeingThroughFogCompressed.z13
SeeingThroughFogCompressed.z07  SeeingThroughFogCompressed.z14

**Comment by VivianGemLee** [comment]
Hi,I have problems when downloading these files.When I click on these files, I get a bunch of messy codes.
![乱码](https://user-images.githubusercontent.com/57170148/174092775-aea25039-9ed1-4680-a1cc-ff373a11e676.png)
I would like to ask you how you downloaded these files.
By the way, I think you also need to download the zip file at the bottom and unzip it.

**Comment by MarioBijelic** [comment]
Hi, 

sorry to hear that you have problems downloading. I was able to reproduce your error and have forwarded the error message. Hope to come back to you as soon as this issue is resolved. 

Best, 
Mario

**Comment by VivianGemLee** [comment]
Thank you so much, this will help me a lot. Looking forward to your reply.

**Comment by sysuzgg** [comment]
Hi,I also have problems when downloading these files. When I click on these files, they download failed after only a few minutes.

**Comment by MarioBijelic** [comment]
Hi @sysuzgg, 

can you please elaborate more on your error. Did you get any error message? I was not able to reproduce the error. 
Are you downloading from within a corporate/university environment? Can you try to download one single file after another? Can you try to logout of your VPN before starting your download?

**Comment by sysuzgg** [comment]
Hi @MarioBijelic ,
I download within an university environment. And I did download one by one. And I logout my VPN before starting my download.   I got a bunch of messy codes.
![图片](https://user-images.githubusercontent.com/43437709/180989127-55bb7648-548c-4e51-a6ea-58f22a37d65c.png)

**Comment by sysuzgg** [comment]
Hi @MarioBijelic ,
 I download within an university environment. And I did download one by  one. And I logout my VPN before starting my download.   I got a bunch of  messy codes. Can you upload your dataset on Baidu Yunpan or Google Drive or e-mail me with ***@***.*** My mailbox can receive 1T of data. and I only need foggy dataset.



------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Send time:&nbsp;Tuesday, Jul 26, 2022 5:04 PM
***@***.***&gt;; 
***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [princeton-computational-imaging/SeeingThroughFog] How to decompress  SeeingThroughFogCompressed (Issue #55)





 
Hi @sysuzgg,
 
can you please elaborate more on your error. Did you get any error message? I was not able to reproduce the error.
 Are you downloading from within a corporate/university environment? Can you try to download one single file after another? Can you try to logout of your VPN before starting your download?

**Comment by soyeongkim** [comment]
Hi [@MarioBijelic](https://github.com/MarioBijelic), I got the same error as @sysuzgg reported. If possible, could you send me the files to my email (kimchuorok@gmail.com)?

**Comment by MarioBijelic** [comment]
Hi @sysuzgg @soyeongkim , 

the issue can be circumvented using firefox on all platforms and right clicking the link. Then you can select "Save as" to download the content without opening it in another window. Hope this helps for now. 

Best, 
Mario

**Comment by cuge1995** [comment]
My solution
```
zip -s- SeeingThroughFogCompressed.zip -O zip_file_full.zip
unzip zip_file_full.zip
```
