### ISSUE TITLE
Download problem, wrong username or password.

### ISSUE THREAD

**Issue by zxczrx123** [princeton-computational-imaging/SeeingThroughFog#56]
I have registered and got a download link. But when when I input the provided user name(dXXXe) and password (BXXX-XXXX-XXXX-XXXY) ,it reminds me of the error.

**Comment by uestcsxt** [comment]
meet the same problem，wrong name or password

**Comment by jihanyang** [comment]
Meet the same issue.

**Comment by MarioBijelic** [comment]
Hi,

I was able to reproduce the error and have forwarded it to the responsible person. I will come back to you as soon as the issue is resolved. 

Best, 
Mario

**Comment by MarioBijelic** [comment]
Hi @jihanyang @uestcsxt @zxczrx123, 

the issue should be resolved now. Please check again. My preferred browser is Chrome. Perhaps you have to register again if the password has changed in the meanwhile.
