### ISSUE TITLE
FIR camera calib

### ISSUE THREAD

**Issue by shiningpure** [princeton-computational-imaging/SeeingThroughFog#59]
I want to do research on FIR camera, where can get the groundtruths and calibration of FIR camera?thanks

**Comment by MarioBijelic** [comment]
@shiningpure the FIR camera is currently not labeled and used as a further reference camera. It provides only little contrast if the lens was covered with water or the whole scene is covered in snow. To show its advantage you may want to also sub select frames from the whole dataset. If you want to extend that work, please reach out directly. 

Best, 
Mario

**Comment by Lucasmogsan** [comment]
> [@shiningpure](https://github.com/shiningpure) the FIR camera is currently not labeled and used as a further reference camera. It provides only little contrast if the lens was covered with water or the whole scene is covered in snow. To show its advantage you may want to also sub select frames from the whole dataset. If you want to extend that work, please reach out directly.
> 
> Best, Mario

@MarioBijelic So this mean you don't have calibration of the FIR camera?
Best, Lucas

**Comment by fabiomontello** [comment]
@MarioBijelic is there any update on the calibration of the FIR camera?
