### ISSUE TITLE
Dataset is too large to download

### ISSUE THREAD

**Issue by soo4826** [princeton-computational-imaging/SeeingThroughFog#61]
Hi,

Thank you for your great job!

I downloaded this for long time.
But the compressed file has error... I can't recognize which file (z01, z02,,,) is wrong

So, is it possible to get part of dataset?
I already see issue #58  but i can find your e-mail addr.
If possible, please let me know your e-mail!

Thanks.

**Comment by MarioBijelic** [comment]
Hi @soo4826, 

can you create a sha256sum for each file. 
I will upload the sha256sum for each file on the server within the next days. Perhaps for now you can first compare the file sizes on the server and locally.

**Comment by soo4826** [comment]
> Hi @soo4826,
> 
> can you create a sha256sum for each file. I will upload the sha256sum for each file on the server within the next days. Perhaps for now you can first compare the file sizes on the server and locally.

Can i get sha256sum file?

**Comment by 853108389** [comment]
@soo4826  Hi, Thank you for your great job!
I have the same problem, I spend a long time downloading datasets, but they always fail to download,  i can not find your e-mail addr too, can you provide me with a subset of the dataset?
Thanks.

**Comment by hiroyukianase** [comment]
I'm also struggling to get all the dataset.
As you said in this loop, I tried to get sha256sum by sha256sum command, but it failed with just "Killed" log. Is there anything that I have to do beforehand?
> $ sha256sum -c SeeingThroughFogCompressed.z01
Killed

> Please download the zip files per sensor and copy all sensorfolders into one common dataset folder. 
In addition, how can I know which file is suitable data? For me, I want front RGB camera, LiDAR, and the annotation on them.

**Comment by soo4826** [comment]
> @soo4826 Hi, Thank you for your great job! I have the same problem, I spend a long time downloading datasets, but they always fail to download, i can not find your e-mail addr too, can you provide me with a subset of the dataset? Thanks.

Sorry, I also have same problem like you.
After downloading whole dataset twice, I have same problem.
I can't extract separate zip file.

I think @MarioBijelic can give sha256sum for us.

**Comment by MarioBijelic** [comment]
Hi @soo4826, 

unfortunately, I am myself still waiting for a response from IT. Truly sorry, for the delay. Can you please post the error message here? For now can you check if the file sizes are at matching with the online indicated size? Perhaps the download did not finish for one of the files.

**Comment by hiroyukianase** [comment]
In addition, there are 19 files, SeeingThroughFogCompressed.z01-19 and SeeingThroughFogCompressed.zip.
Let me confirm which file includes which part of the SeeingThroughFog dataset.
Parhaps, does SeeingThroughFogCompressed,zip include all the data?

**Comment by soo4826** [comment]
> In addition, there are 19 files, SeeingThroughFogCompressed.z01-19 and SeeingThroughFogCompressed.zip. Let me confirm which file includes which part of the SeeingThroughFog dataset. Parhaps, does SeeingThroughFogCompressed,zip include all the data?

I already check my filesize but all of them have same size

Currently, i re-downloading the whole dataset
After download complete, I"ll check it!

<img width="341" alt="image" src="https://user-images.githubusercontent.com/57888866/208820774-172601a1-03a1-417f-bd44-c732dab90b3d.png">

**Comment by hiroyukianase** [comment]
Hmm, I download SeeingThroughFog dataset again and again but still they are not successfully extracted.
Attached the log when I extracted.

How do I download them successfully? In addition, at least I want to clarify which one of the files is corrupted. If the sha256sum  you mentioned above will help me, could you release them?
[extract_stf_fail.txt](https://github.com/princeton-computational-imaging/SeeingThroughFog/files/10283903/extract_stf_fail.txt)

**Comment by soo4826** [comment]
Hi!

I successfully download & extract the whole dataset!

Here's my sha256sum for every files
[SeeingThroughFog_sha256sum.txt](https://github.com/princeton-computational-imaging/SeeingThroughFog/files/10292042/SeeingThroughFog_sha256sum.txt)

After download this file into your dataset download directory,
You can check the integrity of the files with the following command
`$ sha256sum -c SeeingThroughFog_sha256sum.txt`

I use `$ 7z x SeeingThroughFogCompressed..zip` command to extract dataset

**Comment by hiroyukianase** [comment]
Thank you!
Finally, I expand the zip data successfully. 
I expanded it at a directory which is owned by root, though unzip command is done by user. Then I did 7z with sudo. 
Thank you for your support!

**Comment by MarioBijelic** [comment]
@soo4826 I downloaded the current version from the server now as well and can confirm the provided txt file. I will add it to the repository now and add explanations how to extract the dataset. Thank you for your help!

**Comment by sysuzgg** [comment]
@soo4826 can you share me a subset of the dataset? I just want front RGB camera and the annotation on them. I spend a long time downloading datasets, but they always fail to download.
