### ISSUE TITLE
About Rain split

### ISSUE THREAD

**Issue by 853108389** [princeton-computational-imaging/SeeingThroughFog#62]
The splits dir contains fog snow, where is rain?

**Comment by MarioBijelic** [comment]
@853108389 I added a rain split used here https://github.com/marcointrovigne/AdverseWeatherDetection. You can extract the weather labels also from the labeltool labels folder within our dataset. There for each sample a json file is saved containing the meta data including road conditions, weather state and road conditions.

**Comment by 853108389** [comment]
Thank you !!!
This will help me.
Thank you for your support!

**Comment by 853108389** [comment]
I used the provided rain split file to separate the rainy days, however, these images do not look very much like rainy days,
For example, the pedestrians are not wearing umbrellas, and no rain is visible.
